---
name: api_redirect_moved_projects
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128642
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421992
milestone: '16.3'
type: development
group: group::source code
default_enabled: false
