---
name: bitbucket_parallel_importer
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130731
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423530
milestone: '16.4'
type: development
group: group::import and integrate
default_enabled: false
