---
name: browsersdk_tracking
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129517
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/422264
milestone: '16.4'
type: development
group: group::analytics instrumentation
default_enabled: false
