---
name: bulk_imports_batched_import_export
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/124434
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/406559
milestone: '16.2'
type: development
group: group::import and integrate
default_enabled: false
