---
name: cache_client_with_metrics
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/111210
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/392622
milestone: '15.10'
type: development
group: group::source code
default_enabled: false
