---
name: ci_graphql_pipeline_mini_graph
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/116046
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/407818
milestone: '16.1'
type: development
group: group::pipeline authoring
default_enabled: false
