---
name: ci_unlock_pipelines_queue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/124112
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/415503
milestone: '16.2'
type: development
group: group::pipeline security
default_enabled: false
