---
name: ci_variable_drawer
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/126197
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/418005
milestone: '16.3'
type: development
group: group::pipeline security
default_enabled: false
