---
name: clickhouse_ci_analytics
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130211
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424498
milestone: '16.4'
type: development
group: group::runner
default_enabled: false
