---
name: code_suggestions_for_instance_admin_enabled
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122645
rollout_issue_url:
milestone: '16.1'
type: development
group: group::application performance
default_enabled: false
