---
name: combined_analytics_visualization_editor
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131634
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425048
milestone: '16.4'
type: development
group: group::product analytics
default_enabled: false
