---
name: composer_use_ssh_source_urls
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/119739
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/422171
milestone: '16.4'
type: development
group: group::package registry
default_enabled: true
