---
name: coop_header
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131571
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425701
milestone: '16.5'
type: development
group: group::authentication and authorization
default_enabled: false
