---
name: copy_additional_properties_approval_rules
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128259
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423517
milestone: '16.4'
type: development
group: group::code review
default_enabled: false
