---
name: create_runner_machine
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/109983
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/390261
milestone: '15.9'
type: development
group: group::runner
default_enabled: false
