---
name: create_embeddings_with_vertex_ai
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129930
rollout_issue_url:
milestone: '16.4'
type: development
group: group::duo chat
default_enabled: false
