---
name: data_transfer_monitoring
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110211
rollout_issue_url:
milestone: '15.9'
type: development
group: group::source code
default_enabled: false
