---
name: edit_user_profile_vue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122402
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/414552
milestone: '16.1'
type: development
group: group::tenant scale
default_enabled: false
