---
name: elasticsearch_use_traversal_id_optimization
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/108135
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/391286
milestone: '15.9'
type: development
group: group::global search
default_enabled: false
