---
name: enable_exclusive_lease_double_lock_rw
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128083
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421156
milestone: '16.3'
type: development
group: group::scalability
default_enabled: false
