---
name: enforce_global_file_size_limit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128936
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421465
milestone: '16.3'
type: development
group: group::source code
default_enabled: false
