---
name: event_sync_worker_for_click_house
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128628
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421184
milestone: '16.3'
type: development
group: group::optimize
default_enabled: false
