---
name: explain_code_vertex_ai
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/125292
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/416907
milestone: '16.2'
type: development
group: group::source code
default_enabled: false
