---
name: explore_topics_cleaned_path
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122970
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/414793
milestone: '16.1'
type: development
group: group::tenant scale
default_enabled: false
