---
name: fast_forward_merge_trains_support
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122787
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/282442
milestone: '16.1'
type: development
group: group::pipeline execution
default_enabled: false
