---
name: google_play_integration
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110440
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/389611
milestone: '15.10'
type: development
group: group::incubation
default_enabled: false
