---
name: k8s_proxy_pat
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129661
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/422961
milestone: '16.4'
type: development
group: group::environments
default_enabled: true
