---
name: limited_access_modal
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129790
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424877
milestone: '16.4'
type: development
group: group::billing and subscription management
default_enabled: false
