---
name: linear_project_authorization
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117988
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/410459
milestone: '16.0'
type: development
group: group::authentication and authorization
default_enabled: false
