---
name: linked_work_items
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/126980
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/418946
milestone: '16.3'
type: development
group: group::product planning
default_enabled: false
