---
name: merge_trains_create_ref_service
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127531
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/420161
milestone: '16.3'
type: development
group: group::pipeline execution
default_enabled: true
