---
name: packages_dependency_proxy_maven
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/123491
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/415218
milestone: '16.2'
type: development
group: group::package registry
default_enabled: false
