---
name: print_wiki
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/125260
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/414691
milestone: '16.3'
type: development
group: group::knowledge
default_enabled: false
