---
name: resolve_organization_groups
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128733
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421673
milestone: '16.3'
type: development
group: group::tenant scale
default_enabled: true
