---
name: resolvable_issue_threads
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127243
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/419893
milestone: '16.3'
type: development
group: group::project management
default_enabled: true
