---
name: scan_execution_policy_pipelines
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121087
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/415607
milestone: '16.1'
type: development
group: group::security policies
default_enabled: true
