---
name: search_milestones_hide_archived_projects
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130937
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424256
milestone: '16.4'
type: development
group: group::global search
default_enabled: false

