---
name: server_side_frecent_namespaces
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/123554
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/417256
milestone: '16.4'
type: development
group: group::foundations
default_enabled: false
