---
name: skip_validations_during_transitions
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129848
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423092
milestone: '16.4'
type: development
group: group::code review
default_enabled: false
