---
name: ssh_certificates_rest_endpoints
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130866
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424501
milestone: '16.4'
type: development
group: group::source code
default_enabled: false
