---
name: standard_merge_train_ref_merge_commit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129820
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/422724
milestone: '16.4'
type: development
group: group::pipeline execution
default_enabled: true
