---
name: super_sidebar_nav_enrolled
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/119506
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/410121
milestone: '16.0'
type: development
group: group::foundations
default_enabled: true
