---
name: super_sidebar_logged_out
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127756
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/419936
milestone: '16.3'
type: development
group: group::foundations
default_enabled: false
