---
name: ui_for_organizations
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122866
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/414592
milestone: '16.1'
type: development
group: group::tenant scale
default_enabled: false
