---
name: unbatch_graphql_queries
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/117407
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/406765
milestone: '16.0'
type: development
group: group::project management
default_enabled: true
