---
name: use_cluster_shared_state_for_exclusive_lease
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128083
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421156
milestone: '16.3'
type: development
group: group::scalability
default_enabled: false
