---
name: use_primary_and_secondary_stores_for_action_cable
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/126451
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423216
milestone: '16.4'
type: development
group: group::scalability
default_enabled: false
