---
name: use_embeddings_with_vertex
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130421
rollout_issue_url:
milestone: '16.5'
type: development
group: group::duo chat
default_enabled: false
