---
name: use_sub_repositories_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110664
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/392372
milestone: '15.10'
type: development
group: group::container registry
default_enabled: false
