---
name: use_primary_and_secondary_stores_for_workhorse
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/127577
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423420
milestone: '16.4'
type: development
group: group::scalability
default_enabled: false
