---
name: user_search_simple_query_string
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110623
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/391955
milestone: '15.10'
type: development
group: group::global search
default_enabled: false
