---
name: user_profile_overflow_menu_vue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/122971
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/414773
milestone: '16.1'
type: development
group: group::tenant scale
default_enabled: false
