---
name: vulnerability_report_grouping
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129709
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/422509
milestone: '16.4'
type: development
group: group::threat insights
default_enabled: false
