---
name: code_suggestions_tokens_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/120892
rollout_issue_url:
milestone: '16.1'
type: ops
group: group::ai assisted
default_enabled: true
