---
name: search_index_curation_epics
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121635
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/413605
milestone: '16.2'
type: ops
group: group::global search
default_enabled: false
